services:
  # minio:
  #   restart: always
  #   image: minio/minio:RELEASE.2022-03-17T06-34-49Z
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=password
  #   command: server /data --address :9000 --console-address ":9001"

  # minio_create_buckets:
  #   image: minio/mc
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=password
  #   entrypoint:
  #     - "/bin/sh"
  #     - "-c"
  #   command:
  #     - "until (/usr/bin/mc alias set minio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD) do
  #            echo 'Waiting to start minio...' && sleep 1;
  #        done;
  #        /usr/bin/mc mb minio/neon --region=eu-north-1;
  #        exit 0;"
  #   depends_on:
  #     - minio

  pageserver:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon:0.0.1-pg-16
    extra_hosts:
      - "minio:10.43.195.166"

    environment:
      - BROKER_ENDPOINT='http://storage_broker:50051'
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      #- RUST_BACKTRACE=1
    ports:
       #- 6400:6400  # pg protocol handler
       - 9898:9898 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "/usr/local/bin/pageserver -D /data/.neon/
                                   -c \"broker_endpoint=$$BROKER_ENDPOINT\"
                                   -c \"listen_pg_addr='0.0.0.0:6400'\"
                                   -c \"listen_http_addr='0.0.0.0:9898'\"
                                   -c \"remote_storage={endpoint='http://minio:9000',
                                                        bucket_name='neon',
                                                        bucket_region='eu-north-1',
                                                        prefix_in_bucket='/pageserver/'}\""
    depends_on:
      - storage_broker
      # - minio_create_buckets

  safekeeper1:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon:0.0.1-pg-16
    extra_hosts:
      - "minio:10.43.195.166"
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper1:5454
      - SAFEKEEPER_ID=1
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7676:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      # - minio_create_buckets

  safekeeper2:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon:0.0.1-pg-16
    extra_hosts:
      - "minio:10.43.195.166"
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper2:5454
      - SAFEKEEPER_ID=2
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7677:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      # - minio_create_buckets

  safekeeper3:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon:0.0.1-pg-16
    extra_hosts:
      - "minio:10.43.195.166"
    environment:
      - SAFEKEEPER_ADVERTISE_URL=safekeeper3:5454
      - SAFEKEEPER_ID=3
      - BROKER_ENDPOINT=http://storage_broker:50051
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      #- RUST_BACKTRACE=1
    ports:
      #- 5454:5454 # pg protocol handler
      - 7678:7676 # http endpoints
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "safekeeper --listen-pg=$$SAFEKEEPER_ADVERTISE_URL
                    --listen-http='0.0.0.0:7676'
                    --id=$$SAFEKEEPER_ID
                    --broker-endpoint=$$BROKER_ENDPOINT
                    -D /data
                    --remote-storage=\"{endpoint='http://minio:9000',
                                        bucket_name='neon',
                                        bucket_region='eu-north-1',
                                        prefix_in_bucket='/safekeeper/'}\""
    depends_on:
      - storage_broker
      # - minio_create_buckets

  storage_broker:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon:0.0.1-pg-16
    ports:
      - 50051:50051
    command:
      - "storage_broker"
      - "--listen-addr=0.0.0.0:50051"

  compute:
    restart: always
    image: harbor.dh.ksyun.com/bigdata/pbear-neon-cn:0.0.1-pg-16
    extra_hosts:
      - "minio:10.43.195.166"
    environment:
      - PG_VERSION=${PG_VERSION:-16}
      #- RUST_BACKTRACE=1
      - TENANT_ID=a87b11f28feed3f5c1705cd4f9d0fca4
      - TIMELINE_ID=9ec89259964e004f155c323a63b49135
      - SAFEKEEPERS=safekeeper1:5454,safekeeper2:5454,safekeeper3:5454
      - PAGESERVER_CONNSTRING='host=pageserver port=6400'
    ports:
      - 55433:55433 # pg protocol handler
      - 3080:3080 # http endpoints
    entrypoint:
      - "/usr/local/bin/start-cn.sh"
    depends_on:
      - safekeeper1
      - safekeeper2
      - safekeeper3
      - pageserver

  compute_is_ready:
    image: harbor.dh.ksyun.com/bigdata/pbear-pg:0.0.1-pg-16
    entrypoint:
      - "/bin/bash"
      - "-c"
    command:
      - "until pg_isready -h compute -p 55433 -U cloud_admin ; do
            echo 'Waiting to start compute...' && sleep 1;
         done"
    depends_on:
      - compute

  neon-test-extensions:
    profiles: ["test-extensions"]
    image: ${REPOSITORY:-neondatabase}/neon-test-extensions-v${PG_TEST_VERSION:-16}:${TAG:-latest}
    entrypoint:
      - "/bin/bash"
      - "-c"
    command:
      - sleep 1800
    depends_on:
      - compute
